/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.constraint;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int barrierAllowsGoneWidgets = 0x7f030037;
        public static final int barrierDirection = 0x7f030038;
        public static final int chainUseRtl = 0x7f030062;
        public static final int constraintSet = 0x7f030096;
        public static final int constraint_referenced_ids = 0x7f030097;
        public static final int content = 0x7f030098;
        public static final int emptyVisibility = 0x7f0300bf;
        public static final int layout_constrainedHeight = 0x7f03011c;
        public static final int layout_constrainedWidth = 0x7f03011d;
        public static final int layout_constraintBaseline_creator = 0x7f03011e;
        public static final int layout_constraintBaseline_toBaselineOf = 0x7f03011f;
        public static final int layout_constraintBottom_creator = 0x7f030120;
        public static final int layout_constraintBottom_toBottomOf = 0x7f030121;
        public static final int layout_constraintBottom_toTopOf = 0x7f030122;
        public static final int layout_constraintCircle = 0x7f030123;
        public static final int layout_constraintCircleAngle = 0x7f030124;
        public static final int layout_constraintCircleRadius = 0x7f030125;
        public static final int layout_constraintDimensionRatio = 0x7f030126;
        public static final int layout_constraintEnd_toEndOf = 0x7f030127;
        public static final int layout_constraintEnd_toStartOf = 0x7f030128;
        public static final int layout_constraintGuide_begin = 0x7f030129;
        public static final int layout_constraintGuide_end = 0x7f03012a;
        public static final int layout_constraintGuide_percent = 0x7f03012b;
        public static final int layout_constraintHeight_default = 0x7f03012c;
        public static final int layout_constraintHeight_max = 0x7f03012d;
        public static final int layout_constraintHeight_min = 0x7f03012e;
       